### PR TITLE
fix segfault when environment is not BV_OBBRSS type with triangles

### PR DESCRIPTION
**Pull request by pFernbach**
In the shooter, there was a failing assert (in Debug) or a segfault (in Release) when the environment was not composed of fcl::BV_OBBRSS nodes, with modelType==BVH_MODEL_TRIANGLES. 

This temporary fix avoid the failling assert/segfault but is not sufficient : the contact normal is not correctly computed yet in this cases (it is set to +z)

### CODE REVIEW

**Comment by jmirabel** [comment]
After discussion with @pFernbach:
when https://github.com/humanoid-path-planner/hpp-fcl/issues/92 is solved, there won't be a need to put the BV type specifically to get the triangles. This specification is hazardous because it won't work with OBB.

**Comment by stonneau** [comment]
Ok, so should we merge the request or not ?

**Comment by pFernbach** [comment]
I think yes, I opened an issue to remember that we still need to come with a better fix, but I won't have the time to take care of this soon.

**Comment by stonneau** [comment]
Well actually why not raise an error ? I mean if it won't work it won't work no ?

**Comment by pFernbach** [comment]
Teguh need to be able to use the shooter with primitives type. For this use case (and most of the others) it's not an issue if you don't have the correct normal at this step of the algorithm.

**Pull request merged**
